### PR TITLE
documentation for parameter-file option

### PR DESCRIPTION
**Pull request by ramirantala**

### CODE REVIEW

**Comment by hjacobs** [comment]
Thanks!

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
Merging now, feature was released: https://github.com/zalando-stups/senza/releases/tag/1.0.66

**Comment by drummerwolli** [comment]
just to link the PR to the docs: https://github.com/zalando-stups/senza/pull/227

**Pull request merged**
