### PR TITLE
Adding documentation for rsyslog_application_log_format

### PR DESCRIPTION
**Pull request by femueller**
Adding documentation for rsyslog_application_log_format.
This also makes it more clear how to reduce the output for an application produced by the Docker syslog driver.

Signed-off-by: Felix Mueller <felix.mueller@zalando.de>

### CODE REVIEW

**Comment by femueller** [comment]
👍

**Review by christianberg — CHANGES_REQUESTED** [review]
It could be a bit confusing, because the example shows the default output.

It's maybe better to mention the default format (with example output) and then propose a shorter alternative (with example output).

**Comment by femueller** [comment]
@christianberg Added more clearly what the log message will look like after changing the rsyslog_application_log_format

**Review by christianberg — APPROVED** [review]

**Comment by christianberg** [comment]
👍

**Comment by femueller** [comment]
👍

**Pull request merged**
