### PR TITLE
Added node-tokens

### PR DESCRIPTION
**Pull request by yarigpopov**

### CODE REVIEW

**Comment by hjacobs** [comment]
:+1:

**Comment by yarigpopov** [comment]
any other approvers?)

**Comment by hjacobs** [comment]
@chilicoder you can approve yourself

**Comment by yarigpopov** [comment]
Sorry, but I can't. Not authorized

screen shot 2016-10-16 at 15 15 47

**Comment by mikkeloscar** [comment]
@chilicoder you need to add a comment with :+1: first

Edit: you also need to be a public member of Zalando stups org for that to work.

**Comment by yarigpopov** [comment]
how can I become a member?

**Pull request merged**
