### PR TITLE
Revert "Taupage log rotation"

### PR DESCRIPTION
**Pull request by femueller**
Reverts zalando-stups/documentation#124

### CODE REVIEW

**Comment by hjacobs** [comment]
Why?

**Comment by femueller** [comment]
I agree, according to @aermakov-zalando it shouldn't become merged, yet because the AMI is not released yet. But let's keep it in the docs.

**Comment by aermakov-zalando** [comment]
We forgot to fix the documentation when reverting the AMI change and users are already confused. Let's revert it for now and update the docs when we actually release the fix.

**Comment by aermakov-zalando** [comment]
👍

**Comment by njuettner** [comment]
👍

**Pull request merged**
