### PR TITLE
Appdynamics disable logging per default

### PR DESCRIPTION
**Pull request by apfeiffer85**

### CODE REVIEW

**Comment by tuxlife** [comment]
@apfeiffer85 What is the behavior for _old_ application (without update of the senza yaml)

**Comment by apfeiffer85** [comment]
@tuxlife 
If they still want to use AppD logging they have to change the senza.yaml. Therefore we have to announce this change before releasing a new Taupage AMI to give them time to adjust the senza.yaml.

**Comment by tuxlife** [comment]
@apfeiffer85 Please disable AppD logging **only**, if scalyr logging is **enabled**

**Comment by apfeiffer85** [comment]
For the migration time, Logging will be enabled if there is no SCALYR_KEY in the senza.yaml

**Comment by femueller** [comment]
Since AppDynamics isn't really much a part of Taupage I am closing this.

@apfeiffer85 if you have any remarks we can re-open it.

**Pull request closed without merging**
